In [23]:
import numpy as np
import sys

In [6]:
y = [1, 2, 3, 5]
y * 3

x = np.array([1,2,3,4]);
print(x)

x*3

[1 2 3 4]


array([ 3,  6,  9, 12])

## List 

In [6]:
x = [1,2,3,4,5,6,10,3,4,5]
x1 = [0,1,2,3,4,5,6,7,8,9]

In [7]:
len(x1)

10

In [10]:
#(x>=2 and x<7)
x1[2:7]

[2, 3, 4, 5, 6]

In [19]:
x1[:-3]

[0, 1, 2, 3, 4, 5, 6]

In [22]:
x1[-3:]

[7, 8, 9]

In [29]:
x1 = [1,2,3,4]
x2 = np.array([1,2,3,4])
x3 = [4,5,6]
x4 = np.array([4,5,6,7])

In [25]:
print('list: ',x1)
print('array: ', x2)

list:  [1, 2, 3, 4]
array:  [1 2 3 4]


In [30]:
print('list: ',x1 + x3)
print('array: ', x2 + x4)

list:  [1, 2, 3, 4, 4, 5, 6]
array:  [ 5  7  9 11]


In [43]:
# 2 dimensi
data = [[2,   1,   0],
        [4,   1.5, 1],
        [3,   1,   0],
        [3.5, .5,  1],
        [2,   .5,  0],
        [5.5,  1,  1],
        [1,    1,  0]]

In [38]:
array = np.array(data)
array.shape

(7, 3)

In [53]:
x1 = array[:3,0]

In [54]:
x1

array([2., 4., 3.])

In [55]:
x2 = array[:3,1]
x2

array([1. , 1.5, 1. ])

In [56]:
y = array[:3,-1]
y

array([0., 1., 0.])

In [58]:

x = array[3:, :2]
x

array([[3.5, 0.5],
       [2. , 0.5],
       [5.5, 1. ],
       [1. , 1. ]])

## Array

In [9]:
x = np.array([[3,4,5],[1,2,3],[9,8,7]])
print(x)
print('===============================')
y = [[4,4,4],[3,3,3],[7,7,7]]
print('LIST: ',y)
y = np.array(y)
print('ARRAY: \n', y)

[[3 4 5]
 [1 2 3]
 [9 8 7]]
LIST:  [[4, 4, 4], [3, 3, 3], [7, 7, 7]]
ARRAY: 
 [[4 4 4]
 [3 3 3]
 [7 7 7]]


In [8]:
z = x + y
print(z)

[[ 7  8  9]
 [ 4  5  6]
 [16 15 14]]


In [18]:
a = np.array([[1,2,3,4], [1,2,3,4]])
b = np.array([[1,2,3], [1,2,3]])
try:
    c = a + b
    print(c)
except:
    print("error!",sys.exc_info()[0],)


error! <class 'ValueError'>


## Slicing Array

In [1]:
x = np.arange(10,19)
x

NameError: name 'np' is not defined

In [33]:
for i in range(9):
    print(x[i])

10
11
12
13
14
15
16
17
18


In [11]:
for i in x:
    print(i)

10
11
12
13
14
15
16
17
18


In [12]:
for i in range(9):
    if i>=4 and i<8 : 
        print(x[i])

14
15
16
17


In [35]:
print(x[])

[14 15 16 17]


In [21]:
x = np.arange(15).reshape(3,5)
x  = x + 3.2
print(x)

[[ 3.2  4.2  5.2  6.2  7.2]
 [ 8.2  9.2 10.2 11.2 12.2]
 [13.2 14.2 15.2 16.2 17.2]]


In [22]:
# get value from matrix x
for i in range (3):
    for j in range (5):
        print('data: ', x[i][j])
    

data:  3.2
data:  4.2
data:  5.2
data:  6.2
data:  7.2
data:  8.2
data:  9.2
data:  10.2
data:  11.2
data:  12.2
data:  13.2
data:  14.2
data:  15.2
data:  16.2
data:  17.2


In [27]:
for i in range (3):
    for j in range (5):
        if (i>=1) and ((j>=2) and(j<4)): 
            print('data: ', x[i][j])

data:  10.2
data:  11.2
data:  15.2
data:  16.2


In [28]:
x[1:,2:4]

array([[10.2, 11.2],
       [15.2, 16.2]])

In [41]:
#Array 3 dimension

x_3D = np.arange(27).reshape(3,3,3)
x_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [44]:
print(x_3D[:,1:,1:])

[[[ 4  5]
  [ 7  8]]

 [[13 14]
  [16 17]]

 [[22 23]
  [25 26]]]
